<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="stembot_bringup">

    <xacro:property name="chassis_length" value="0.22" />
    <xacro:property name="chassis_breadth" value="0.22" />
    <xacro:property name="chassis_height" value="0.005" />

    <xacro:property name="frame_mass" value="0.859" />
    <xacro:property name="payload_mass" value="0.0" />

    <xacro:property name="wheel_length" value="0.03" />
    <xacro:property name="wheel_radius" value="0.035" />
    <xacro:property name="chassis_wheel_x_offset" value="${(chassis_length/2)-0.038}" />
    <xacro:property name="chassis_wheel_offset_height" value="${-0.026}" />

    <xacro:property name="wheel_separation" value="0.26" />
    <xacro:property name="wheel_mass" value="0.1" />

    <xacro:property name="caster_pos_x" value="${(chassis_length/2)-0.06}" />
    <xacro:property name="caster_pos_y" value="${(chassis_breadth/2)-0.1}" />

    <!-- Wheel xacro -->
    <xacro:macro name="wheel" params="prefix reflect_x reflect_y">

        <link name="${prefix}_wheel_link">

            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <material name="black" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
            </collision>
            <inertial>
                <mass value="${wheel_mass}" />
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
                <inertia
                    ixx="${1/12*wheel_mass*(3*(wheel_radius*wheel_radius)+(wheel_length*wheel_length))}"
                    iyy="${1/12*wheel_mass*(3*(wheel_radius*wheel_radius)+(wheel_length*wheel_length))}"
                    izz="${1/2*wheel_mass*(wheel_radius*wheel_radius)}"
                    ixy="0.0" iyz="0.0" ixz="0.0" />
            </inertial>

        </link>

        <joint name="${prefix}_wheel_joint" type="continuous">

            <parent link="base_link" />
            <child link="${prefix}_wheel_link" />
            <origin
                xyz="${-reflect_x*(chassis_wheel_x_offset)} ${-reflect_y*(wheel_separation/2)} ${-(chassis_wheel_offset_height+(chassis_height/2))}"
                rpy="${pi/2} 0 0" />
            <axis xyz="0.0 0.0 -1.0" />
            <limit effort="0.56" velocity="12.56" />

        </joint>

    </xacro:macro>

    <!-- Caster wheel xacro -->
    <xacro:macro name="caster_wheel" params="prefix reflect">

        <link name="${prefix}_caster_link">

            <visual>
                <origin
                    xyz="0 0 0"
                    rpy="0 0 0" />
                <geometry>
                    <sphere radius="0.009" />
                </geometry>
                <material name="black" />
            </visual>
            <collision>
                <origin
                    xyz="0 0 0"
                    rpy="0 0 0" />
                <geometry>
                    <sphere radius="0.009" />
                </geometry>
            </collision>

        </link>
        <joint name="${prefix}_caster_joint" type="fixed">

            <parent link="base_link" />
            <child link="${prefix}_caster_link" />
            <origin xyz="${caster_pos_x} ${-reflect*caster_pos_y} ${-(chassis_wheel_offset_height+(chassis_height/2)+wheel_radius-0.01)}" rpy="0 0 0" />

        </joint>

    </xacro:macro>

    <!-- Frame -->
    <!-- TODO: Fix and verify interial parameters for this -->
    <link name="base_footprint">
    </link>
    <link name="base_link">

        <visual>
            <origin
                xyz="${(chassis_length/2)} ${-(chassis_breadth/2)} ${-chassis_height/2}"
                rpy="0 0 ${pi/2}" />
            <geometry>
                <mesh filename="package://stembot_bringup/urdf/meshes/chassis.stl" />
            </geometry>
            <material name="silver" />
        </visual>
        <collision>
            <origin
                xyz="${(chassis_length/2)} ${-(chassis_breadth/2)} ${-chassis_height/2}"
                rpy="0 0 ${pi/2}" />
            <geometry>
                <mesh filename="package://stembot_bringup/urdf/meshes/chassis.stl" />
            </geometry>
        </collision>
        <inertial>
            <mass value="${frame_mass + payload_mass}" />
            <origin xyz="0.110000 0.110344 0.053552" rpy="0 0 0" />
            <inertia
                ixx="0.000006"
                iyy="0.000006"
                izz="0.000008"
                ixy="0.0" iyz="0.0" ixz="0.0" />
        </inertial>

    </link>
    <joint name="base_joint" type="fixed">

        <parent link="base_footprint" />
        <child link="base_link" />

    </joint>

    <xacro:wheel prefix="right" reflect_x="1" reflect_y="1" />
    <xacro:wheel prefix="left" reflect_x="1" reflect_y="-1" />

    <xacro:caster_wheel prefix="center" reflect="0" />

</robot>