ekf_filter_node:
    ros__parameters:
        frequency       : 20.0
        two_d_mode      : true
        publish_tf      : true
        map_frame       : map
        odom_frame      : odom
        base_link_frame : base_footprint
        world_frame     : odom

        #        [x_pos   , y_pos    , z_pos,
        #         roll    , pitch    , yaw,
        #         x_vel   , y_vel    , z_vel,
        #         roll_vel, pitch_vel, yaw_vel,
        #         x_accel , y_accel  , z_accel]

        odom0: /wheel_odom
        odom0_config: [false, false, false,
                       false, false, false,
                       true, true, false,
                       false, false, false,
                       false, false, false]

        imu0: /imu_filtered
        imu0_config: [false, false, false,
                      false, false, true,
                      false, false, false,
                      false, false, true,
                      false, false, false]